addSbtPlugin("com.typesafe.play" %% "sbt-plugin" % "2.7.0")
//addSbtPlugin("com.typesafe.play" %% "sbt-plugin" % "2.6.21")
addSbtPlugin("org.foundweekends.giter8" %% "sbt-giter8-scaffold" % "0.11.0")
addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.8.2")
addSbtPlugin("com.scalapenos" % "sbt-prompt" % "1.0.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.4")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.8")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
